before:
  hooks:
    - go mod download
    - mkdir -p bin && GOBIN=$PWD/bin go get golang.org/x/tools/cmd/stringer
    - ./bin/stringer -type=Name ./oids
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
    goarm:
      - 5
      - 6
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    format_overrides:
    - goos: windows
      format: zip
    files:
    - LICENSE*
    - README*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "SNAPSHOT-{{ .Commit }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
