// Code generated by "stringer -type=Name ./oids"; DO NOT EDIT.

package oids

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SysUpTime-0]
	_ = x[ArrisRouterHardwareVersion-1]
	_ = x[ArrisRouterFirmwareVersion-2]
	_ = x[ArrisRouterAdminTimeout-3]
	_ = x[ArrisRouterBssSSID-4]
	_ = x[ArrisRouterWPAPreSharedKey-5]
	_ = x[ArrisRouterBssActive24GHz-6]
	_ = x[ArrisRouterBssActive5GHz-7]
}

const _Name_name = "SysUpTimeArrisRouterHardwareVersionArrisRouterFirmwareVersionArrisRouterAdminTimeoutArrisRouterBssSSIDArrisRouterWPAPreSharedKeyArrisRouterBssActive24GHzArrisRouterBssActive5GHz"

var _Name_index = [...]uint8{0, 9, 35, 61, 84, 102, 128, 153, 177}

func (i Name) String() string {
	if i < 0 || i >= Name(len(_Name_index)-1) {
		return "Name(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Name_name[_Name_index[i]:_Name_index[i+1]]
}
